# Generated by Django 5.0.6 on 2024-07-08 07:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myaccount", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="full_profile_id",
            field=models.CharField(
                blank=True, editable=False, max_length=255, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="profile_id",
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
        migrations.AlterUniqueTogether(
            name="profile",
            unique_together={("user", "profile_id")},
        ),
    ]
