# Generated by Django 5.0.6 on 2024-07-08 07:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myaccount", "0002_profile_full_profile_id_profile_profile_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="full_profile_id",
            field=models.CharField(editable=False, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile_id",
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
