# Generated by Django 5.0.6 on 2024-07-08 08:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myaccount", "0004_alter_profile_full_profile_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="full_profile_id",
            field=models.CharField(editable=False, max_length=255, unique=True),
        ),
    ]
