# Generated by Django 5.0.6 on 2024-07-10 05:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myaccount", "0006_alter_profile_full_profile_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="attendance_dates",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="profile",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
