# Generated by Django 5.0.6 on 2024-07-11 06:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myaccount", "0007_readinghistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="readinghistory",
            name="story_id",
            field=models.IntegerField(default=4962),
        ),
    ]
