# Generated by Django 5.0.6 on 2024-07-01 01:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0002_readerstory_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="readerstory",
            name="category",
            field=models.CharField(default="Uncategorized", max_length=100),
        ),
    ]
