# Generated by Django 5.0.6 on 2024-07-04 02:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0003_readerstory_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("story_id", models.IntegerField()),
                ("question", models.TextField()),
            ],
        ),
    ]
