# Generated by Django 5.0.6 on 2024-07-11 04:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0006_delete_review"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ChatHistory",
        ),
        migrations.DeleteModel(
            name="ReaderStory",
        ),
    ]
