# Generated by Django 5.0.6 on 2024-07-11 05:25

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("quiz", "0007_delete_chathistory_delete_readerstory"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("story_id", models.IntegerField()),
                ("question", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="ReaderStory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="non title", max_length=200)),
                ("body", models.TextField()),
                ("category", models.CharField(default="Uncategorized", max_length=100)),
            ],
            options={
                "db_table": "reader_story",
            },
        ),
    ]
