# Generated by Django 5.0.6 on 2024-07-08 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0006_delete_review"),
        ("review", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="story_id",
        ),
        migrations.AddField(
            model_name="review",
            name="story",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="quiz.readerstory",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="story_title",
            field=models.CharField(default="Unknown", max_length=200),
        ),
        migrations.AddField(
            model_name="review",
            name="title",
            field=models.CharField(default="Untitled", max_length=200),
        ),
    ]
