# Generated by Django 5.0.6 on 2024-07-08 05:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("review", "0003_alter_review_story"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="story",
        ),
        migrations.AddField(
            model_name="review",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
