# Generated by Django 5.0.6 on 2024-07-08 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myaccount", "0001_initial"),
        ("review", "0004_remove_review_story_review_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="profile",
            field=models.ForeignKey(
                default=99999,
                on_delete=django.db.models.deletion.CASCADE,
                to="myaccount.profile",
            ),
        ),
    ]
