# Generated by Django 5.0.6 on 2024-07-08 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myaccount", "0001_initial"),
        ("review", "0006_alter_review_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="profile",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                to="myaccount.profile",
            ),
        ),
    ]
