# Generated by Django 5.0.6 on 2024-07-08 08:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("review", "0007_alter_review_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="story_title",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="review",
            name="title",
            field=models.CharField(default="", max_length=200),
        ),
    ]
