# Generated by Django 5.0.6 on 2024-07-08 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myaccount", "0005_alter_profile_full_profile_id"),
        ("review", "0008_alter_review_story_title_alter_review_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="myaccount.profile"
            ),
        ),
    ]
