# Generated by Django 5.0.6 on 2024-07-11 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reader", "0005_alter_story_keywords"),
        ("review", "0010_alter_review_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="story",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="reader.story",
            ),
        ),
    ]
