# Generated by Django 5.0.6 on 2024-07-11 05:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("review", "0011_review_story"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="story",
        ),
    ]
