# Generated by Django 5.0.6 on 2024-07-12 00:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("review", "0012_remove_review_story"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="author_thoughts",
            field=models.TextField(blank=True, default="내 생각은..."),
        ),
        migrations.AddField(
            model_name="review",
            name="ending",
            field=models.TextField(blank=True, default="결국에..."),
        ),
        migrations.AddField(
            model_name="review",
            name="main_character",
            field=models.TextField(blank=True, default="이이야기의 주인공은..."),
        ),
    ]
