# Generated by Django 5.0.6 on 2024-07-12 02:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("review", "0013_review_author_thoughts_review_ending_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="author_thoughts",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="review",
            name="ending",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="review",
            name="main_character",
            field=models.TextField(default=""),
        ),
    ]
