# Generated by Django 5.0.6 on 2024-06-27 08:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reader", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="story",
            name="tag",
            field=models.ManyToManyField(blank=True, to="reader.tag"),
        ),
    ]
