# Generated by Django 5.0.6 on 2024-07-01 01:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reader", "0002_alter_story_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="category",
            field=models.CharField(default="Uncategorized", max_length=100),
        ),
    ]
