# Generated by Django 5.0.6 on 2024-07-10 02:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reader", "0003_story_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="keywords",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="story",
            name="theme",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
