# Generated by Django 5.0.6 on 2024-07-12 01:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reader", "0003_story_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="LogEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime", models.DateTimeField(auto_now_add=True)),
                ("question", models.TextField()),
                ("answer", models.TextField()),
            ],
        ),
    ]
