# Generated by Django 5.0.6 on 2024-07-12 04:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reader", "0004_logentry"),
        ("reader", "0005_alter_story_keywords"),
    ]

    operations = []
